branches:
  only:
  - master

language: go
env:
  - GO111MODULE=on

install: true

go:
  - 1.14.x
services:
  - docker

script:
  - cd cmd/server
  - cp "$(go env GOROOT)/misc/wasm/wasm_exec.js" .
  - go generate
  - GOOS=js GOARCH=wasm go build -o main.wasm
  - CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o server server.go
 - cd ../../
  - docker build -t ilanpillemer/health:${TRAVIS_COMMIT::8} .
  - docker build -t ilanpillemer/health:latest .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push ilanpillemer/health:${TRAVIS_COMMIT::8}
  - docker push ilanpillemer/health:latest

before_install:
  - go get -u github.com/vugu/vgrun
  - vgrun -install-tools
